FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install numpy
RUN pip install requests
RUN pip install kubernetes
RUN pip install gymnasium

COPY master.py .

CMD ["python", "master.py"]
