apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-node
spec:
  selector:
    matchLabels:
      app: master-pod
  template:
    metadata:
      labels:
        app: master-pod
    spec:
      volumes:
      - name: model-volume
        emptyDir: {}
      containers:
      - name: master-container
        image: freewer/master:latest
        command: ["python", "-u", "/app/master.py", "$(GRID_SIZE)", "$(EPISODES)", "$(EPISODES_PER_WORKER)"]
        env:
          - name: GRID_SIZE
            valueFrom:
              configMapKeyRef:
                name: my-variables
                key: grid_size
          - name: EPISODES
            valueFrom:
              configMapKeyRef:
                name: my-variables
                key: episodes
          - name: EPISODES_PER_WORKER
            valueFrom:
              configMapKeyRef:
                name: my-variables
                key: episodes_per_worker
        volumeMounts:
        - name: model-volume
          mountPath: /app/model
