apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-node
spec:
  selector:
    matchLabels:
      app: master-pod
  template:
    metadata:
      labels:
        app: master-pod
    spec:
      containers:
      - name: master-container
        image: freewer/master:latest