apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-node
spec:
  replicas: 4  # Adjust the number of replicas as per your requirements
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-container
        image: freewer/worker:latest
        command: ["python", "-u", "/app/worker.py"]
