apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-node
spec:
  replicas: 3  # Adjust the number of replicas as per your requirements
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-container
        image: freewer/worker:latest
        # env:
        # - name: MASTER_NODE_URL
        #   value: http://master-node  # Use the service name of master node
